"""Generate `src/pyunicode/tables.rs` from the reference CPython's own Unicode data.

The metadata compiler has to fold strings exactly as Python 0.5.2 did
(`str.lower`, `str.casefold`, `str.isspace`, `str.isdecimal`,
`unicodedata.digit`, `unicodedata.combining`), and Rust's std tables track a
newer Unicode version than CPython 3.12 (UCD 15.0). So the tables are taken
from the interpreter itself rather than from a crate.

Run with the 0.5.2 reference interpreter:

    ~/.cache/mokuro-bunko-demo/ref052/bin/python crates/bunko-library/scripts/gen_unicode_tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "pyunicode" / "tables.rs"
SIGMA = 0x3A3


def chars():
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        yield cp, chr(cp)


def ranges(cps):
    out = []
    for cp in cps:
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def rust_str(s: str) -> str:
    return '"' + "".join(f"\\u{{{ord(c):x}}}" for c in s) + '"'


def main() -> None:
    lower = []
    casefold = []
    space = []
    decimal = []
    digit = []
    combining = []
    cased = []
    ignorable = []
    for cp, c in chars():
        if cp != SIGMA and c.lower() != c:
            lower.append((cp, c.lower()))
        if c.casefold() != c:
            casefold.append((cp, c.casefold()))
        if c.isspace():
            space.append(cp)
        if c.isdecimal():
            decimal.append((cp, unicodedata.decimal(c)))
        elif unicodedata.digit(c, None) is not None:
            digit.append((cp, unicodedata.digit(c)))
        if unicodedata.combining(c):
            combining.append((cp, unicodedata.combining(c)))
        if cp != SIGMA:
            t1 = ("A" + c + "Σ").lower()[-1] == "ς"
            t2 = ("AΣ" + c).lower()[1] == "ς"
            if t1 and t2:
                ignorable.append(cp)
            elif t1 and not t2:
                cased.append(cp)
    # Decimal digits come in runs whose values count up by one.
    dec_runs = []
    for cp, value in decimal:
        if dec_runs and dec_runs[-1][1] == cp - 1 and dec_runs[-1][2] + (cp - dec_runs[-1][0]) == value:
            dec_runs[-1][1] = cp
        else:
            dec_runs.append([cp, cp, value])
    lines = [
        "// @generated by scripts/gen_unicode_tables.py from CPython "
        f"{sys.version.split()[0]} (UCD {unicodedata.unidata_version}). Do not edit.",
        "",
        f'pub const UNIDATA_VERSION: &str = "{unicodedata.unidata_version}";',
        "",
        "/// `str.lower()` per code point (U+03A3 handled by the final-sigma rule).",
        "pub static LOWER: &[(u32, &str)] = &[",
    ]
    lines += [f"    (0x{cp:x}, {rust_str(s)})," for cp, s in lower]
    lines += ["];", "", "/// `str.casefold()` per code point.", "pub static CASEFOLD: &[(u32, &str)] = &["]
    lines += [f"    (0x{cp:x}, {rust_str(s)})," for cp, s in casefold]
    lines += ["];", "", "/// `str.isspace()`.", "pub static SPACE: &[u32] = &["]
    lines += [f"    0x{cp:x}," for cp in space]
    lines += ["];", "", "/// `str.isdecimal()` runs: (first, last, value of first).",
              "pub static DECIMAL: &[(u32, u32, u8)] = &["]
    lines += [f"    (0x{a:x}, 0x{b:x}, {v})," for a, b, v in dec_runs]
    lines += ["];", "", "/// `unicodedata.digit` for characters that are NOT decimal.",
              "pub static DIGIT_NOT_DECIMAL: &[(u32, u8)] = &["]
    lines += [f"    (0x{cp:x}, {v})," for cp, v in digit]
    lines += ["];", "", "/// `unicodedata.combining(c) != 0` ranges.", "pub static COMBINING: &[(u32, u32)] = &["]
    lines += [f"    (0x{a:x}, 0x{b:x})," for a, b in ranges(cp for cp, _ in combining)]
    lines += ["];", "", "/// CPython `_PyUnicode_IsCased` (for non-case-ignorable characters).",
              "pub static CASED: &[(u32, u32)] = &["]
    lines += [f"    (0x{a:x}, 0x{b:x})," for a, b in ranges(cased)]
    lines += ["];", "", "/// CPython `_PyUnicode_IsCaseIgnorable`.", "pub static CASE_IGNORABLE: &[(u32, u32)] = &["]
    lines += [f"    (0x{a:x}, 0x{b:x})," for a, b in ranges(ignorable)]
    lines += ["];", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}: lower={len(lower)} casefold={len(casefold)} space={len(space)} "
          f"decimal_runs={len(dec_runs)} digit={len(digit)} cased={len(ranges(cased))} "
          f"ignorable={len(ranges(ignorable))}")


if __name__ == "__main__":
    main()
