"""Generate src/unicode_tables.rs from the reference Python's unicodedata.

The queue's natural sort must agree with 0.5.2 character for character, and
0.5.2 used Python's own `str.casefold`, `str.isalnum` and `re`'s `\\d` + `int(ch)`.
Taking the tables from the same interpreter (CPython 3.12, Unicode 15.0) makes
the Rust port agree by construction instead of by a third-party crate's
Unicode version. NFKC is NOT generated here (it needs composition data); it
comes from the `unicode-normalization` crate.

Run: ~/.cache/mokuro-bunko-demo/ref052/bin/python tools/gen_unicode_tables.py
"""

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "unicode_tables.rs"


def ranges(pred):
    out = []
    start = None
    for cp in range(sys.maxunicode + 1):
        if 0xD800 <= cp <= 0xDFFF:
            ok = False
        else:
            ok = pred(chr(cp))
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, sys.maxunicode))
    return out


def main():
    lines = [
        "// @generated by tools/gen_unicode_tables.py from CPython "
        f"{sys.version.split()[0]} (Unicode {unicodedata.unidata_version}). Do not edit.",
        "",
        "/// `(code point, str.casefold())` for every code point the fold changes.",
        "pub(crate) static CASEFOLD: &[(u32, &str)] = &[",
    ]
    for cp in range(sys.maxunicode + 1):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        folded = ch.casefold()
        if folded != ch:
            esc = "".join(f"\\u{{{ord(c):x}}}" for c in folded)
            lines.append(f'    (0x{cp:x}, "{esc}"),')
    lines.append("];")
    lines.append("")
    lines.append("/// Inclusive ranges of code points where `str.isalnum()` is true.")
    lines.append("pub(crate) static ALNUM: &[(u32, u32)] = &[")
    for a, b in ranges(str.isalnum):
        lines.append(f"    (0x{a:x}, 0x{b:x}),")
    lines.append("];")
    lines.append("")
    # Decimal digits (`re` \d on str, `str.isdecimal`) as runs whose value is
    # (cp - start + first_value).
    lines.append("/// `(first, last, value of first)`: runs of decimal digits (`\\d`), ascending values.")
    lines.append("pub(crate) static DECIMAL: &[(u32, u32, u32)] = &[")
    runs = []
    for cp in range(sys.maxunicode + 1):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        if not ch.isdecimal():
            continue
        value = unicodedata.decimal(ch)
        if runs and runs[-1][1] == cp - 1 and runs[-1][2] + (cp - runs[-1][0]) == value:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp, value])
    for a, b, v in runs:
        lines.append(f"    (0x{a:x}, 0x{b:x}, {v}),")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
