//! Pure, synchronous OCR scheduling math for mokuro-bunko, ported from the
//! 0.5.2 Python (`ocr/job_order.py`, `eta.py`, `congestion.py`,
//! `throughput.py`, `volume_outlook.py`, the verdict half of
//! `engine_runner.py`, and the pure helpers of `watcher.py` /
//! `processor.py`). See `docs/rust-port/spec/ocr-scheduling.md` §4, 8, 12, 18–21.
//!
//! Numbers, rounding (Python's half-to-even `round`), ordering and the
//! sentences shown in the UI are reproduced exactly; `tests/golden/` holds
//! fixtures generated by the 0.5.2 code and the tests replay them.
//!
//! No I/O except the small helpers that read and write the three JSON state
//! files (`.ocr-failures.json`, `.ocr-congestion.json`, `.ocr-bench.json`)
//! in their 0.5.2 format, and [`rate::FilePriors`], which reads the latter two.

pub mod bench;
pub mod bench_file;
pub mod breaker;
pub mod congestion;
pub mod eft;
pub mod failures;
pub mod job_order;
pub mod outlook;
pub mod plan;
pub mod precision;
pub mod py;
pub mod pyjson;
pub mod rate;
pub mod speed;
pub mod throughput;
mod unicode_tables;

use std::path::PathBuf;

/// Errors of the state-file helpers (the math itself does not fail).
#[derive(Debug, thiserror::Error)]
pub enum SchedError {
    #[error("could not write {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

pub use congestion::{
    average_runs, build_record, pipeline_verdict, summarize, summarize_event_stats, widen_target,
};
pub use eft::{EftDecision, EftLane, EftLeft, earliest_finish_claim};
pub use job_order::{natural_key, order_jobs};
pub use plan::{Lane, PlanInputs, Pricing, QueuePlan, plan_queue, progress_metrics};
pub use py::iso_utc;
pub use rate::{
    RateEstimate, RateModel, StartupEstimate, emission_rate, fit_volume_cost, rate_key,
};
