//! The tray icons, generated by `packaging/icons/generate.py` and embedded here.

use crate::model::IconState;

macro_rules! tray_png {
    ($state:literal, $size:literal) => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../packaging/icons/png/tray-",
            $state,
            "-",
            $size,
            ".png"
        ))
    };
}

/// macOS draws status items 22 pt high (44 px on Retina); Windows and the Linux
/// panels scale a 32 px image well.
#[cfg(target_os = "macos")]
fn png(state: IconState) -> &'static [u8] {
    match state {
        IconState::Idle => tray_png!("idle", "44"),
        IconState::Working => tray_png!("working", "44"),
        IconState::Paused => tray_png!("paused", "44"),
        IconState::Attention => tray_png!("attention", "44"),
    }
}

#[cfg(not(target_os = "macos"))]
fn png(state: IconState) -> &'static [u8] {
    match state {
        IconState::Idle => tray_png!("idle", "32"),
        IconState::Working => tray_png!("working", "32"),
        IconState::Paused => tray_png!("paused", "32"),
        IconState::Attention => tray_png!("attention", "32"),
    }
}

/// Decode to `(rgba, width, height)`.
pub fn rgba(state: IconState) -> Result<(Vec<u8>, u32, u32), png::DecodingError> {
    let mut decoder = png::Decoder::new(std::io::Cursor::new(png(state)));
    decoder.set_transformations(png::Transformations::normalize_to_color8());
    let mut reader = decoder.read_info()?;
    let mut buf = vec![0; reader.output_buffer_size().unwrap_or(0)];
    let info = reader.next_frame(&mut buf)?;
    buf.truncate(info.buffer_size());
    let rgba = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::Rgb => buf
            .as_chunks::<3>()
            .0
            .iter()
            .flat_map(|&[r, g, b]| [r, g, b, 255])
            .collect(),
        png::ColorType::GrayscaleAlpha => buf
            .as_chunks::<2>()
            .0
            .iter()
            .flat_map(|&[g, a]| [g, g, g, a])
            .collect(),
        _ => buf.iter().flat_map(|&g| [g, g, g, 255]).collect(),
    };
    Ok((rgba, info.width, info.height))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_state_decodes() {
        for s in [
            IconState::Idle,
            IconState::Working,
            IconState::Paused,
            IconState::Attention,
        ] {
            let (px, w, h) = rgba(s).unwrap();
            assert_eq!(px.len(), (w * h * 4) as usize);
            assert!(w >= 32 && w == h);
            // Transparent corner (rounded square), opaque centre.
            assert_eq!(px[3], 0);
            let c = ((h / 2) * w + w / 2) as usize * 4;
            assert_eq!(px[c + 3], 255);
        }
    }
}
