package app.mokuro.bunko

import android.app.Activity
import android.os.Bundle
import android.widget.Button
import android.widget.TextView

/**
 * Third-party notices: THIRD-PARTY-LICENSES.md is generated by build.sh from xtask's
 * licence collector (the same file the desktop archives ship) plus the crates only the
 * Android library uses.
 */
class LicensesActivity : Activity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_licenses)
        Ui.applyInsets(findViewById(R.id.root))
        findViewById<Button>(R.id.back).setOnClickListener { finish() }
        val text = findViewById<TextView>(R.id.text)
        Thread {
            val body = buildString {
                append(getString(R.string.app_name)).append(" ").append(BuildInfo.versionName(this@LicensesActivity))
                append(" — Mozilla Public License 2.0\n\n")
                append(getString(R.string.android_licences_intro)).append("\n\n")
                for (name in listOf("ANDROID-NOTICES.txt", "THIRD-PARTY-LICENSES.md")) {
                    runCatching { assets.open(name).bufferedReader().use { append(it.readText()).append("\n\n") } }
                        .onFailure { append("($name is missing from this build)\n\n") }
                }
            }
            runOnUiThread { text.text = body }
        }.start()
    }
}
